-
  branches:
    except:
      - release
      - /v\d\.\d\.\d/

  skip_branch_with_pr: true
  skip_tags: true

  os: Visual Studio 2013

  configuration: development

  platform:
    - x64

  version: "{build}"

  build: off
  shallow_clone: true

  clone_folder: c:\node-raw-socket

  init:
    - ps: set-location -path c:\node-raw-socket

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    matrix:
      # - nodejs_version: 4
      - nodejs_version: 6
      # - nodejs_version: 7

  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - npm install --msvs_version=2013
    # - 7z a c:\node-raw-socket\node-raw-socket.winx86.zip c:\node-raw-socket\build\Release\raw.node
 
  artifacts:
    - path: build\Release\raw.node

  deploy:
    - provider: GitHub
      description: Great release for us
      # artifact: /node-raw-socket/
      draft: true
      prerelease: false
      force_update: true
      auth_token:
        secure: txo0j3thuQZP+B3m2XOTbRAwpWj7rVp2+mTIVmV+8uBoYcyNhmRfGc4WrviKVRuh
      on:
        branch: prebuilt                # release from master branch only
        appveyor_repo_tag: false       # deploy on tag push only
